# http://module-build.sourceforge.net/META-spec.html
name:         DBD-ADO
version:      2.92
version_from: lib/DBD/ADO.pm
installdirs:  site
requires:
    DBI: 0
    Win32::OLE: 0.16
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
